### PR TITLE
make code better

### PR DESCRIPTION
**Pull request by sertdfyguhi**
hehe

### CODE REVIEW

**Review by SpeckyYT — CHANGES_REQUESTED** [review]
Why JSDocs if we have typings?

**Comment by sertdfyguhi** [comment]
> Why JSDocs if we have typings?

What typings?

**Comment by SpeckyYT** [comment]
> > Why JSDocs if we have typings?
> 
> What typings?

`index.d.ts`
and tbh, I don't quite like some styles used in this PR (e.g. indentation after `obj\n.prop`, no indentation on ternary and other)

**Comment by sertdfyguhi** [comment]
> > > Why JSDocs if we have typings?
> > 
> > 
> > What typings?
> 
> `index.d.ts`

Having both is better than just having one

**Comment by sertdfyguhi** [comment]
> > > Why JSDocs if we have typings?
> > 
> > 
> > What typings?
> 
> `index.d.ts`
> and tbh, I don't quite like some styles used in this PR (e.g. indentation after `obj\n.prop`, no indentation on ternary and other)

Sure i can put them back

**Pull request merged**
